---
title: "Lab 10 - Grading the professor"
author: "Anaelle Gackiere"
date: "03-27-2026"
output: github_document
---

Here is a link to the [lab instructions](https://datascience4psych.github.io/DataScience4Psych/lab10.html).

## Load Packages and Data

```{r load-packages, message=FALSE, warning=FALSE}
library(tidyverse) 
library(tidymodels)
library(openintro)
```

## Exercise 1

The distribution of scores is negatively skewed, so students are relatively generous. The mean score is 4.175, and the minimum score given was 2.3 (at least not a 0!).

```{r exercise1_code}
# descriptives
summary(evals$score)

# visualization
ggplot(evals, aes(x = score)) +
  geom_bar( fill = "plum4", bins = 30) +
  theme_minimal()

```

## Exercise 2

```{r exercise2_code}
ggplot(data = evals, aes(x = score, y = bty_avg)) +
  geom_jitter() +
  labs(title = "Profesor Evaluation Score vs Average Beauty",
       x = "Score",
       y = "Average Beauty") +
  theme_classic() 
```

## Additional Exercises

*Repeat the format above for additional exercises.*

## Hint

For Exercise 12, the `relevel()` function can be helpful!
